# Build settngs
title: Efarmoges Pliroforikis
author: Stathis Kaloudis
logo: aegean_logo.png
description: This website presents...

markdown: kramdown
# theme: minima
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
